
clone_depth: 5

platform:
  - x64

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  PATH: C:\Python37-x64;%PATH%

install:
  - cmd: pip install git+https://github.com/mdavidsaver/ci-core-dumper#egg=ci-core-dumper

build_script:
  - cmd: echo nothing to build

test_script:
  - cmd: ci-core-dumper -v install
  - cmd: ci-core-dumper crash --direct # remove after verification

on_finish:
  - cmd: ci-core-dumper report

notifications:
  - provider: GitHubPullRequest
