
clone_depth: 5

platform:
  - x64

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  PATH: C:\Python37-x64;%PATH%

install:
  - cmd: python -V
  - cmd: python -m pip install git+https://github.com/mdavidsaver/ci-core-dumper#egg=ci-core-dumper

build_script:
  - cmd: echo nothing to build

test_script:
  - cmd: python -m ci_core_dumper -v install
  - cmd: echo tests which might crash

on_finish:
  - cmd: python -m ci_core_dumper report

notifications:
  - provider: GitHubPullRequest
