os: linux

addons:
  apt:
    packages:
    - gdb

install:
  - sudo python -m pip install git+https://github.com/mdavidsaver/ci-core-dumper#egg=ci-core-dumper

before_script:
  - sudo python -m ci_core_dumper install

script:
  - ulimit -c unlimited

after_failure:
  - python -m ci_core_dumper report
