name: Demo ci-core-dumper

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Crash Test
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: mdavidsaver/ci-core-dumper@master
      - name: Test
        run: |
          ulimit -c unlimited
          # commands which may crash"
          #   ...
          #
          # or may use:  exec ...
          # which raises core limit on Linux
          #python -m ci_core_dumper exec ...
